Vlki\ExceptorBundle\Entity\UnprocessedException:
    type: entity
    table: unprocessed_exception
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        data:
            type: text