Vlki\ExceptorBundle\Entity\Exception:
  type: entity
  table: exception
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    received_at:
      type: datetime
    data:
      type: text