Vlki\ExceptorBundle\Entity\Exception:
  type: entity
  table: exception
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    received_at:
      type: datetime
    sg_server:
      type: array
    sg_session:
      type: array
    sg_get:
      type: array
    sg_post:
      type: array
    exception_data:
      type: array
    signature:
      type: string
      length: 32